### PR TITLE
[Feature] Add a cmdline option to use gnome-screenshot instead of pyqt to capture screenshots

### LINKED ISSUE #110: [Feature] Add a cmdline option to use `gnome-screenshot` instead of pyqt to capture screenshots
Under linux, it is possible to use `gnome-screenshot` to capture screenshots which makes multiple monitor support very easy. #57 

The implementation is very trivial and I can open a pull request for that soon.

### PR DESCRIPTION
**Pull request by kxxt**
Close #110

### CODE REVIEW

**Comment by kxxt** [comment]
After I got the webview working, I can confirm that this feature works fine.

**Comment by lukas-blecher** [comment]
Thank you, I will test if for myself and then merge the pull request

**Comment by lukas-blecher** [comment]
Sorry for the wait. And thank you again!

**Comment by kxxt** [comment]
I should also thank you for your continued dedication to this awesome open source software. :heart: 
We all understand that being a maintainer can be hard, because creating something new is more fun than maintaining an existing repo.

**Comment by jakob1379** [comment]
Woop woop - thank you so much!

**Pull request merged**
