### PR TITLE
Data parallelism【multi-gpu train】+pure ViT work + small modify

### PR DESCRIPTION
**Pull request by TITC**
## pure ViT structure
We discussed pure ViT structure at https://github.com/lukas-blecher/LaTeX-OCR/discussions/131 .

> 1. Initially, I used a pure ViT  ([6ecc3f4](https://github.com/lukas-blecher/LaTeX-OCR/commit/6ecc3f486b8172183442dc17fef4cceb2a7f6541)). But the encoder was just not performing very well. The model produced latex code but it has nothing to do with the input image.

And I do come up with same result, the model can't converge. In fact, I would hope that larger pure vit can achieve high performance, it really frustrated me. But in recent days, https://github.com/lukas-blecher/LaTeX-OCR/issues/147#issuecomment-1125837771 give me some idea, because the training loss curve is so familiar like pure vit training curve, so I think the reason why pure vit can't fit maybe due to batch size.

I taken and modified [models.py](https://github.com/lukas-blecher/LaTeX-OCR/blob/844bc219a9469fa7e9dfc8626f74a705bd194d69/models.py) from 844bc219a9469fa7e9dfc8626f74a705bd194d69.

Here is the good news, it's working. 

image

How to use
```shell
# for vit
 python -m pix2tex.train --config model/settings/config-vit.yaml --structure vit
# for hybrid, default is hybrid
 python -m pix2tex.train --config model/settings/config.yaml --structure hybrid
 python -m pix2tex.train --config model/settings/config.yaml

```

## Data parallelism

I think multi-GPU training can save more time and a larger batch size, so refer to some documents and blogs and make such changes.
Also, it's compatible with one GPU.

How to use
```shell
#for one GPU
export CUDA_VISIBLE_DEVICES=6
 python -m pix2tex.train --config model/settings/config-vit.yaml --structure vit
#for multi GPU
export CUDA_VISIBLE_DEVICES=6,7
 python -m pix2tex.train --config model/settings/config-vit.yaml --structure vit
```

References:
1. [Technique 1: Data Parallelism](https://www.run.ai/guides/multi-gpu/pytorch-multi-gpu-4-techniques-explained)
2. [data_parallel_tutorial.ipynb](https://colab.research.google.com/github/pytorch/tutorials/blob/gh-pages/_downloads/63ecfdf27b96977f3a89015f60065a2b/data_parallel_tutorial.ipynb)
3. https://github.com/jytime/Mask_RCNN_Pytorch/issues/2#issuecomment-423718196

## small modify
I think both hybrid and pure vit work together, why not put them together. so create a folder named as `structures`.

---
the branch is based on 720978d8c469780ed070d041d5795c55b705ac1b, please feel free to correct any inappropriate code.😁

### CODE REVIEW

**Comment by lukas-blecher** [comment]
That's great news! 
I've restructured the models code a little bit so that it is easier to call and removed some duplicate code.
Feel free to take a look, and tell me if I messed up somewhere.

**Comment by TITC** [comment]
Thanks a lot, I can benefit greatly from each pull request that you reviewed.

---

test again for both vit and hybrid, only have below problem. 

```shell
Traceback (most recent call last):                                                                   
  File "/root/anaconda3/envs/latex_ocr_test/lib/python3.7/runpy.py", line 193, in _run_module_as_main 
    "__main__", mod_spec)                                                                                                                                                                                  
  File "/root/anaconda3/envs/latex_ocr_test/lib/python3.7/runpy.py", line 85, in _run_code                                                                                                                 
    exec(code, run_globals)                                                                          
  File "/yuhang/LaTeX-OCR/pix2tex/train.py", line 102, in <module>                                                                                                                                         
    train(args)                                                                                                                                                                                            
  File "/yuhang/LaTeX-OCR/pix2tex/train.py", line 27, in train                              
    model = get_model(args, training=True)                                                           
  File "/yuhang/LaTeX-OCR/pix2tex/models/utils.py", line 49, in get_model                            
    en_attn_layers = encoder.module.attn_layers if available_gpus > 1 else encoder.attn_layers                                                                                                             
  File "/root/anaconda3/envs/latex_ocr_test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1186, in __getattr__                                                                             
    type(self).__name__, name))
AttributeError: 'CustomVisionTransformer' object has no attribute 'attn_layers'
```

If there is a better way to re-write 0aefdbf052e4072ad7de150eee5ef84da5f205f4, please modify it.

**Comment by lukas-blecher** [comment]
Sorry, my fault. I didn't try with `wandb: True` 

Why don't you just watch the `model = Model(encoder, decoder, args)`?

**Comment by TITC** [comment]
because I don't know what it used to do before, like the `random seeds` stuff, haha

I read the [doc ](https://docs.wandb.ai/guides/integrations/pytorch#logging-gradients-with-wandb.watch)and found it related to the `gradient`. maybe it can give some further clues around fit model.
image

 Thanks for your guidance.

**Comment by TITC** [comment]
based on this [stackoverflow QA](https://stackoverflow.com/a/56783306/11430711), it seems git pull command fetch 6c531057f4232750cd6607ddd6cfcba5f5673f54 and automatically merge to local, then commit 4ffbeca499c6933ecc4ab10806f46961f907ed3b, it's kind beyond my expectation. I thought it only commit 5cbbcb929874a0f55434dd4a328ea38ee8683d12.

**Comment by lukas-blecher** [comment]
Before I merge this: There is something that went wrong along the way.
When I try to load the pretrained model, the decoder architecture has changed
```bash
        Missing key(s) in state_dict: "decoder.net.attn_layers.layers.0.1.to_out.weight", "decoder.net.attn_layers.layers.0.1.to_out.bias", "decoder.net.attn_layers.layers.1.1.to_out.weight", "decoder.net.attn_layers.layers.1.1.to_out.bias", "decoder.net.attn_layers.layers.2.1.net.0.0.weight", "decoder.net.attn_layers.layers.2.1.net.0.0.bias", "decoder.net.attn_layers.layers.3.1.to_out.weight", "decoder.net.attn_layers.layers.3.1.to_out.bias", "decoder.net.attn_layers.layers.4.1.to_out.weight", "decoder.net.attn_layers.layers.4.1.to_out.bias", "decoder.net.attn_layers.layers.5.1.net.0.0.weight", "decoder.net.attn_layers.layers.5.1.net.0.0.bias", "decoder.net.attn_layers.layers.6.1.to_out.weight", "decoder.net.attn_layers.layers.6.1.to_out.bias", "decoder.net.attn_layers.layers.7.1.to_out.weight", "decoder.net.attn_layers.layers.7.1.to_out.bias", "decoder.net.attn_layers.layers.8.1.net.0.0.weight", "decoder.net.attn_layers.layers.8.1.net.0.0.bias", "decoder.net.attn_layers.layers.9.1.to_out.weight", "decoder.net.attn_layers.layers.9.1.to_out.bias", "decoder.net.attn_layers.layers.10.1.to_out.weight", "decoder.net.attn_layers.layers.10.1.to_out.bias", "decoder.net.attn_layers.layers.11.1.net.0.0.weight", "decoder.net.attn_layers.layers.11.1.net.0.0.bias".
        Unexpected key(s) in state_dict: "decoder.net.attn_layers.layers.0.1.to_out.0.weight", "decoder.net.attn_layers.layers.0.1.to_out.0.bias", "decoder.net.attn_layers.layers.1.1.to_out.0.weight", "decoder.net.attn_layers.layers.1.1.to_out.0.bias", "decoder.net.attn_layers.layers.2.1.net.0.proj.weight", "decoder.net.attn_layers.layers.2.1.net.0.proj.bias", "decoder.net.attn_layers.layers.3.1.to_out.0.weight", "decoder.net.attn_layers.layers.3.1.to_out.0.bias", "decoder.net.attn_layers.layers.4.1.to_out.0.weight", "decoder.net.attn_layers.layers.4.1.to_out.0.bias", "decoder.net.attn_layers.layers.5.1.net.0.proj.weight", "decoder.net.attn_layers.layers.5.1.net.0.proj.bias", "decoder.net.attn_layers.layers.6.1.to_out.0.weight", "decoder.net.attn_layers.layers.6.1.to_out.0.bias", "decoder.net.attn_layers.layers.7.1.to_out.0.weight", "decoder.net.attn_layers.layers.7.1.to_out.0.bias", "decoder.net.attn_layers.layers.8.1.net.0.proj.weight", "decoder.net.attn_layers.layers.8.1.net.0.proj.bias", "decoder.net.attn_layers.layers.9.1.to_out.0.weight", "decoder.net.attn_layers.layers.9.1.to_out.0.bias", "decoder.net.attn_layers.layers.10.1.to_out.0.weight", "decoder.net.attn_layers.layers.10.1.to_out.0.bias", "decoder.net.attn_layers.layers.11.1.net.0.proj.weight", "decoder.net.attn_layers.layers.11.1.net.0.proj.bias".
```

I'll look into it

**Comment by lukas-blecher** [comment]
One other thing I just remembered:

What if you train you model on multiple GPUs and then try to finetune or evaluate on a single GPU machine?
Won't there be an error because of the `nn.DataParallel` wrapper? I think the state dict should be saved without the wrapper, which makes saving and loading a bit more complicated

**Comment by TITC** [comment]
I will test that situation right now.

> What if you train you model on multiple GPUs and then try to finetune or evaluate on a single GPU machine?


There is no rush to merge this PR, I think we have plenty of time to test and troubleshoot the situation.

**Comment by TITC** [comment]
You are right, I am dealing it.

> What if you train you model on multiple GPUs and then try to finetune or evaluate on a single GPU machine?

**Comment by TITC** [comment]
I referenced [nn.DataParallel.forward](https://github.com/pytorch/pytorch/blob/eeabab03e7a7399c454ce69ad7aea20d885a4929/torch/nn/parallel/data_parallel.py#L147-L169)  and [parallelism_tutorial ](https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html), the solution is gradually emerging. Write a function only use multi-gpu when be called, no need wrapper anymore or change any other part code to compatible with `nn.DataParallel`

But I encounter some AssertionError after some steps, hope I can solve it as soon as possible in the next few days.

```shell
Loss: 0.9900:   4%|█████▍                                                                                                                                               | 289/7891 [01:35<41:53,  3.03it/s]
Traceback (most recent call last):
  File "/root/anaconda3/envs/latex_ocr_test/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/latex_ocr_test/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/yuhang/LaTeX-OCR/pix2tex/train.py", line 123, in <module>
    train(args)
  File "/yuhang/LaTeX-OCR/pix2tex/train.py", line 75, in train
    encoded = data_parallel(encoder,inputs=im[j:j+microbatch].to(device), device_ids=[0,1,2])
  File "/yuhang/LaTeX-OCR/pix2tex/train.py", line 29, in data_parallel
    outputs = nn.parallel.parallel_apply(replicas, inputs,kwargs)
  File "/root/anaconda3/envs/latex_ocr_test/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 40, in parallel_apply
    assert len(modules) == len(kwargs_tup)
AssertionError
```

**Comment by TITC** [comment]
which way do you think is better to multi-GPU? @lukas-blecher 

1. use system environment to specify GPU index
```shell
#multi-gpu
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
python -m pix2tex.train --config model/settings/config-vit.yaml
#one-gpu
export CUDA_VISIBLE_DEVICES=0
python -m pix2tex.train --config model/settings/config-vit.yaml
```
2. write GPU indices to config.yaml
```yaml
#multi-gpu
gpu_indices: [0,1,2,3,4,5,6,7]
python -m pix2tex.train --config model/settings/config-vit.yaml
#one GPU
gpu_indices: [0]
python -m pix2tex.train --config model/settings/config-vit.yaml
#or default is one GPU and set gpu_indices:null
gpu_indices:null
```

**Comment by lukas-blecher** [comment]
Option 1 is better.
I think it is straight forward selecting the gpus with that option.
This is how I belive it works (not 100% sure): Say
```bash
export CUDA_VISIBLE_DEVICES=2,3
```
in python `cuda:0` and `cuda:1` will correspond to the devices 2, 3.

Also you don't need to change the yaml setting when running the script on another machine or multiple times at the same time

**Comment by TITC** [comment]
Agree, one command then problem solved. 

After a couple of hours of usage, I found that if the GPU cards are shared with different guys at the server, some of them directly occupied part memory with several GPUs. Then I need to check the Linux history command or search at Google to copy `export CUDA_VISIBLE_DEVICES=xxxxx`  switch to memory available gpus, one time is convenient but frequently makes it kinda annoying. 

so I set option 1 as default and compatible with option 2 for this situation. =￣ω￣=

---
code tested in
- [x] model trained on one GPU env loaded at multi-GPU env, vit.
- [x] model trained on multi GPU env and loaded at one GPU env, vit.
- [x] training in multi GPU, both vit and hybrid.
- [x] training in one GPU, both vit and hybrid.

**Comment by lukas-blecher** [comment]
I've never seen the `nn.parallel` before. Did you notice performance differences between the `nn.DataParellel` class and the new method?

**Comment by TITC** [comment]
pytorch lib first import `from .data_parallel import DataParallel, data_parallel` at  [nn/parallel/__init__.py](https://github.com/pytorch/pytorch/blob/eeabab03e7a7399c454ce69ad7aea20d885a4929/torch/nn/parallel/__init__.py#L3), then `from .parallel import DataParallel ` at [nn/__init__.py](https://github.com/pytorch/pytorch/blob/eeabab03e7a7399c454ce69ad7aea20d885a4929/torch/nn/__init__.py#L3). 

`nn.DataParellel` is [nn.parallel.data_parallel.DataParellel](https://github.com/pytorch/pytorch/blob/eeabab03e7a7399c454ce69ad7aea20d885a4929/torch/nn/parallel/data_parallel.py#L40), it's basically a part of `nn.parallel`.

**Comment by lukas-blecher** [comment]
Ok I see, you basically reimplemented that function. Looks fine, should also have the same performance.

Another way would have been to do something like this, when saving:
```python
new_state_dict = OrderedDict()
for k, v in state_dict.items():
    name = k[:7]  # remove `module.`
    new_state_dict[name] = v
```
It's quite hacky. I like your solution better.

**Comment by TITC** [comment]
batchsize: 512
micro_batchsize: 128
gpu: RTX3090*3

each trained 2 epoch

1. this method
```shell
BLEU: 0.637, ED: 3.04e-01, ACC: 0.292:   0%|                                                                                                                                              | 0/389 [00:00<?, ?it/s]
Loss: 0.0629:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 1016/1067 [26:33<01:19,  1.57s/it]
BLEU: 0.599, ED: 3.38e-01, ACC: 0.321:   3%|███▍                                                                                                                                 | 10/389 [00:16<10:07,  1.60s/it]
Loss: 0.0806:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 1019/1067 [23:02<01:05,  1.36s/it]
```

2. nn.DataParallel

I create a branch from ff2641cd4bddaa672e22823bb0a405f8e87bcf15
```shell
git checkout -b nn_parallel ff2641cd4bddaa672e22823bb0a405f8e87bcf15
```
then

```shell
BLEU: 0.069, ED: 2.81e+00, ACC: 0.039:   0%|                                                                                                                                              | 0/389 [00:08<?, ?it/s]
Loss: 0.3394:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 1016/1067 [22:50<01:08,  1.35s/it]
BLEU: 0.340, ED: 7.07e-01, ACC: 0.192:   3%|███▍                                                                                                                                 | 10/389 [00:22<14:18,  2.26s/it]
Loss: 0.1870:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 1019/1067 [23:06<01:05,  1.36s/it]
```

**Comment by TITC** [comment]
> Another way would have been to do something like this

Got it, will try this tomorrow.

**Comment by lukas-blecher** [comment]
> > Another way would have been to do something like this
> 
> Got it, will try this tomorrow.

I don't think this will be necessary. You found a better solution already.

> An alternative solution that comes up to me is re-write model.forward and includes encoder.forward and decoder.forward in it,

This. That's the way to go. Handeling the parallel data stuff in the forward method of `Model` is the way to go.
Move the current `forward` to `generate` or something similar and replace all model calls in eval and cli with the gererate function.

**Comment by TITC** [comment]
Gotcha, I will implement it ASAP.

**Comment by TITC** [comment]
Test again, seems same with [2. nn.DataParallel](https://github.com/lukas-blecher/LaTeX-OCR/pull/150#issuecomment-1131780320)

```shell
BLEU: 0.069, ED: 2.81e+00, ACC: 0.039:   0%|                                                                                                                                              | 0/389 [00:08<?, ?it/s]
Loss: 0.3394:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 1016/1067 [21:28<01:04,  1.27s/it]
BLEU: 0.341, ED: 7.05e-01, ACC: 0.192:   3%|███▍                                                                                                                                 | 10/389 [00:22<14:31,  2.30s/it]
Loss: 0.1870:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 1019/1067 [21:29<01:00,  1.27s/it]
```

**Comment by lukas-blecher** [comment]
The `generate` function doesn't exist for the `LatexOCR` class. I've corrected this from a previous commit, replaced the correct lines of code with the new `generate` function of `Model`.

Also moved the `data_parallel` into the `Model` class.

**Comment by TITC** [comment]
Test again or are there any other things we need to do?

**Comment by TITC** [comment]
Oops, the same config as previous but something happened. 
```shell
Loss: 0.4742:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 999/1067 [21:24<01:27,  1.29s/it]
Traceback (most recent call last):
  File "/root/anaconda3/envs/pix2tex/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/pix2tex/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/yuhang/LaTeX-OCR/pix2tex/train.py", line 116, in <module>
    train(args)
  File "/yuhang/LaTeX-OCR/pix2tex/train.py", line 81, in train
    bleu_score, edit_distance, token_accuracy = evaluate(model, valdataloader, args, num_batches=int(args.valbatches*e/args.epochs), name='val')
  File "/root/anaconda3/envs/pix2tex/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/yuhang/LaTeX-OCR/pix2tex/eval.py", line 54, in evaluate
    dec = model.generate(im.to(device), temperature=args.get('temperature', .2))
  File "/root/anaconda3/envs/pix2tex/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/yuhang/LaTeX-OCR/pix2tex/models/utils.py", line 37, in generate
    eos_token=self.args.eos_token, context=self.encoder(x), temperature=temperature)
  File "/root/anaconda3/envs/pix2tex/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/yuhang/LaTeX-OCR/pix2tex/models/transformer.py", line 40, in generate
    out = torch.cat((out, sample), dim=-1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 1 but got size 20 for tensor number 1 in the list.
```
I am looking at it, do you have any idea about it?

**Comment by lukas-blecher** [comment]
Should be fine now

**Comment by TITC** [comment]
Yeah, it's work fine.
```shell
BLEU: 0.180, ED: 1.12e+00, ACC: 0.092:   0%|                                                                                                                                              | 0/389 [00:01<?, ?it/s]
Loss: 0.3501:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 1016/1067 [23:01<01:09,  1.36s/it]
Loss: 0.4497:  30%|██████████████████████████████████████████████▋                                                                                                             | 319/1067 [07:17<11:13,  1.11it/s]
```

**Comment by Sanster** [comment]
@TITC Hello, recently I have been studying your various code contributions in this project, and I have learned a lot. Recently, I have also been training a model for latex recognition, and I would like to ask you a question: Have you trained a better recognition model using a pure ViT architecture as the backbone?

**Comment by TITC** [comment]
no....., I know some info not sure if I can help you. Pre-trained pure ViT seems better than train from scratch. see [TrOCR](https://arxiv.org/abs/2109.10282) for detail.

> TrOCR uses the pre-trained image Transformer and text Transformer models, which take advantages of largescale unlabeled data for image understanding and language modeling, with no need for an external language model.

Here is a quick start for TrOCR finetuning implemented by [huggingface](https://colab.research.google.com/github/NielsRogge/Transformers-Tutorials/blob/master/TrOCR/Fine_tune_TrOCR_on_IAM_Handwriting_Database_using_native_PyTorch.ipynb).

**Comment by Sanster** [comment]
Thank you for your response. I found that the [Pix2Text](https://github.com/breezedeus/Pix2Text) project uses trocr for training. His model's performance is good. According to this [issue](https://github.com/breezedeus/Pix2Text/issues/89), the author used over two million data points for training.

**Pull request merged**
