### PR TITLE
add support for readline

### LINKED ISSUE #177: [feature] Support readline hotkey?
That is input `<C-B>/<C-F>/...` can move the cursor in `Predict LaTeX code for image ("?"/"h" for help).` Thanks.

### PR DESCRIPTION
**Pull request by Freed-Wu**
Fix #177

#181 is too large because it contains too many commits which have different
functions, so I think if it is split to many PRs, you can review it more
easily. This PR cherry-picks the commits only related to readline and squash them
to one commit. Thanks.

### CODE REVIEW

**Comment by Freed-Wu** [comment]
I believe this PR can work even if on windows.

And prompt-toolkit or pyreadline3 should be another unrelated PR.

**Comment by lukas-blecher** [comment]
Awesome! 
Tested it on my windows machine, works fine.

**Comment by Freed-Wu** [comment]
How about providing a command opiton `--history` to point the readline history? Just like `--config`.

**Comment by lukas-blecher** [comment]
Why would you want to change the history file?

**Comment by Freed-Wu** [comment]
Maybe someone want to `pix2tex --history=/dev/null` (for linux) or `pix2tex --history=nul` (for windows) to make sure all history will not be recorded?

**Pull request merged**
