### PR TITLE
Make gui better and fix bug of QWebEngine doesn't display eq on linux

### PR DESCRIPTION
**Pull request by muyuuuu**
1. `app.exec_()` is pyqt4's method, `app.exec()` is pyqt5's method
2. I found that math equation displays well in windows but doesn't display in linux platform as description in #109 , so I add system judgment statements by `os` module to make it work correctly
3. I read `gui.py` and find `displayPrediction` function will be called three times in one snip: 

`toggleProcessing` function is responsible for the modification of the button signal, not the display function. So I think that is redundancy and inelegant, it should be decoupled here. 
4. Removed some unused modules
5. The code in both linux( arch ) and windows test passed

### CODE REVIEW

**Comment by lukas-blecher** [comment]
Thanks for the contribution. Will have a look at it later

**Comment by lukas-blecher** [comment]
The loading wheel doesn't appear for me anymore now

**Comment by muyuuuu** [comment]
> 

emmmm, what's meaning?

**Comment by lukas-blecher** [comment]
Before there was a loading wheel spinning during computation (see gif in readme) 
With your changes that doesn't appear anymore for me.

**Comment by muyuuuu** [comment]
I'm sorry it was my oversight

https://github.com/lukas-blecher/LaTeX-OCR/blob/1a109bcc19e7623c436e2fabd93de98704a7ef03/pix2tex/gui.py#L104

this line shoule be keep.

**Comment by HuangJianxjtu** [comment]
I also met the PyQt5  problem  on ubuntu 20.04

**Pull request merged**
