### PR TITLE
GUI: enable copy latex to clipboard

### PR DESCRIPTION
**Pull request by Khalilsqu**
This will add a copy button to copy the latex code in the GUI directly into the OS clipboard.
@katie-lim

copybutton

### CODE REVIEW

**Comment by lukas-blecher** [comment]
Hi, thanks for your contribution.
The predicted latex code is already copied into the clipboard after a sucessful prediction in [pix2tex.py#L99](https://github.com/lukas-blecher/LaTeX-OCR/blob/b7bb48505a3d26cf33e18f6cfcb86a4dbf48c391/pix2tex.py#L99).
I'm not sure if an extra button is actually needed. What do you think?

**Comment by Khalilsqu** [comment]
Yes, that is true, I was not aware of that. Sorry for wasting your time. No need of this PR.

**Comment by Khalilsqu** [comment]
Also, thank you for this awesome project. I used [Mathpix](https://mathpix.com/) but it is not free.

**Comment by lukas-blecher** [comment]
No worries!
Thank you again.

**Pull request closed without merging**
