### PR TITLE
img has been cut off abnormally

### PR DESCRIPTION
**Pull request by TITC**
assume We have an image, with a size of  (352,31), and the `min_dimensions` is (32,32). Then it's qualified `any` judgment. Image (352,31) is being pasted to a new blank Image whose size is (32,32). 

```python
        if any([s < min_dimensions[i] for i, s in enumerate(img.size)]):
            padded_im = Image.new('L', min_dimensions, 255)
            padded_im.paste(img, img.getbbox())
            img = padded_im
```

### CODE REVIEW

**Comment by TITC** [comment]
Here is the picture we have.

**Comment by TITC** [comment]
And I wonder why we need the [minmax_size](https://github.com/lukas-blecher/LaTeX-OCR/blob/4e0f0a639880f2676541b115dadadceba7243bba/pix2tex.py#L29-L40) function?  Does this is used to prevent downsample process dimension not meeting the requirements?
image

**Comment by lukas-blecher** [comment]
Thank you very much!
The idea behind the `minmax_size` function is that the ViT can accept only a very discrete amount of image sizes. The formula you showed above is for CNNs right?
That's what `pad` is for but it doesn't cover the edge case of a too large image.
Come to think about it the function would be fine without any of the `min_dimensions` stuff.

**Comment by TITC** [comment]
Thanks for the explanation, seems I need to reread  ViT's paper carefully and its GitHub repository.

**Pull request merged**
