### PR TITLE
fix multi-screen screenshot #194

### PR DESCRIPTION
**Pull request by ficapy**
My system is macOS Ventura 13.2.1 with dual screens, and I can only take screenshots on one screen when I use it because `self.setGeometry` is fixed.
So I added the ability to re-call `self.setGeometry` when the cursor switches from one screen to the other, so that the screenshot can be taken on the new screen normally
Also, `QtCore.Qt.Key_Escape` is not working anymore because of upgrading to PyQt6

### CODE REVIEW

**Comment by Pedsurgeon1** [comment]
QtCore.Qt.Key_Escape is not working anymore because of upgrading to PyQt6

this makes it crashes with me when it takes a screen shot 

how to solve please

**Comment by ficapy** [comment]
> QtCore.Qt.Key_Escape is not working anymore because of upgrading to PyQt6
> 
> this makes latexocr crash with me when it takes a screenshot
> 
> how to solve, please

try installing the latest version
```
pip install "git+https://github.com/lukas-blecher/LaTeX-OCR.git#egg=pix2tex[gui]"
```

**Comment by Pedsurgeon1** [comment]
> 
> try installing the latest version
> 
> ```
> pip install "git+https://github.com/lukas-blecher/LaTeX-OCR.git#egg=pix2tex[gui]"
> ```

Thanks a lot, @ficapy it works now 

I have only one more question 

could I install now newer versions of these packages? 

pip install PyQt6==6.5.1 PyQt6-Qt6==6.5.1 PyQt6-WebEngine-Qt6==6.5.1 PyQt6-WebEngine
pip install PySide6-Essentials==6.5.1 PySide6==6.5.1 PySide6-Addons==6.5.1 shiboken6==6.5.1

I had to downgrade them all to 6.5.1 according to some recommendations here while I was trying to make latexocr work

Thank you again

**Comment by ficapy** [comment]
I just tried installing it on OSX and encountered the same issue. according to `setup.py`
```
gui = [
    'PyQt6',
    'PyQt6-WebEngine',
    'pyside6',
    'pynput',
    'screeninfo',
]
```

It may not be compatible with the latest version of PyQt6. changing it to a fixed version should work:
```
gui = [
    'PyQt6==6.5.0,
    'PyQt6-WebEngine==6.5.0',
    'pyside6==6.5.0',
    'pynput',
    'screeninfo',
]
```

```
git clone https://github.com/lukas-blecher/LaTeX-OCR.git
cd LaTeX-OCR/
# modify setup.py
pip install .[gui]
pix2tex_gui
```

**Comment by Pedsurgeon1** [comment]
Thank you @ficapy 
it now works with me on 6.5.1

just by installing these packages 
pip install PyQt6==6.5.1 PyQt6-Qt6==6.5.1 PyQt6-WebEngine-Qt6==6.5.1 PyQt6-WebEngine
pip install PySide6-Essentials==6.5.1 PySide6==6.5.1 PySide6-Addons==6.5.1 shiboken6==6.5.1

and after that, I installed latexocr according to  your comment
pip install "git+https://github.com/lukas-blecher/LaTeX-OCR.git#egg=pix2tex[gui]"


I hope you will be able to solve all the issues related newer versions soons 

Thanks a lot for your cooperation and feedback

**Pull request merged**
